name: ebay job
on:
  push:
    branch: [ "master" ]
  
  workflow_dispatch:
jobs:
  app_one:
    steps:
        - name: step 1 - Checkout branch master
          uses: actions/checkout@v1
        
        - name: step 2 - Set - up JDK 1.8
          uses: actions/setup-java@v1
          with: 
            java-version: '1.8'
            distribution: 'temurin'
            cache: maven

        - name: Step 3 - Build with Maven
          run: |
            echo building with maven
            mvn -B package --file pom.xml
